edu/urls.py
from django.urls import path
from . import views

app_name = 'edu'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('tag', views.TagStudy.as_view(), name='tag_study'),
    path('new', views.NewContent.as_view(), name='new_content'),
]

lets/urls.py
from django.contrib import admin
from django.urls import path, include
import edu.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('edu/', include('edu.urls')),      # edu app 의 url 을 include 한다.
    path('', edu.views.Index.as_view()),    # 첫 페이지의 url 에 app 이름이 들어가지 않도록 수정한다.
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

edu/models.py
from django.db import models

# Create your models here.
class Feed(models.Model):
    content = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="image/", max_length=255, null=True, blank=True)

edu/views.py
from django.views.generic import View
from django.shortcuts import get_object_or_404, render, redirect
from .models import Feed
#현재폴더의 models 라는 파일에서 Feed라는 이름의 class를 가져오세요.

class Index(View):
    template_name = 'index.html'

    def get(self, request):
        return render(request, self.template_name)
    
class TagStudy(View):
    template_name = 'tag_study.html'

    def get(self, request):
        feeds = Feed.objects.all()

        return render(request, self.template_name,
                      {'feed_list' : feeds})
    
class NewContent(View):
    template_name = 'upload_form.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        #content 정보를 전달받는다
        param = request.POST.get('content', '')
        param2 = request.FILES.get('up_photo', False)
        #화면에서 확인 하기위해 출력
        print(f"param:{param}")
        feed = Feed(content = param, photo = param2)
        feed.save()
        #받는게 완료되면 /edu/tag 로 이동
        return redirect('edu:tag_study')
        

edu/templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <title>렛츠코딩 입니다.</title>
        {% block extrahead %}
        {% endblock %}
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

edu/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <p>환영합니다.</p>
    <p>
        <a href="https://www.naver.com">네이버</a>
        <br>
        <a href="http://letscoding.kr">
            <img src="http://letscoding.kr/img/logo.png" width='30' height='30'>
        </a>
        <br>
    </p>
{% endblock %}

edu/templates/input.html
<!DOCTYPE html>
<html>
<body>

<h2>Input Forms</h2>

<form action="/action_page.php">
  <label for="fname">First name:</label><br>
  <input type="text" id="fname" name="fname" placeholder="성을 입력하세요."><br>
  
  <label for="lname">Last name:</label><br>
  <input type="text" id="lname" name="lname" placeholder="이름을 입력하세요."><br>
  
  <label for="mypwd">password:</label><br>
  <input type="password" id="mypwd" name="pwd" placeholder="비밀번호를 입력하세요."><br>
  
  <label for="age">age:</label><br>
  <input type="number" id="age" name="myage" placeholder="나이를 입력하세요."/><br><br>
  
  <input type="file" accept=".jpg, .png, .pdf" name="myflies"/><br><br>
  
  <input type="color" value="#ff0000" name="mycolor"/><br><br>
  
  <input type="radio" name="contry" value="kr" checked/>한국
  <input type="radio" name="contry" value="cn"/>중국
  <input type="radio" name="contry" value="jp"/>일본
  <input type="radio" name="contry" value="nk"/>북한<br><br>
  
  <input type="checkbox" checked/>치킨
  <input type="checkbox" />피자
  <input type="checkbox" />마라탕
  <input type="checkbox" />삼겹살
  <input type="checkbox" />탕후루<br><br>
  
  <select name="grade">
  	<option value="1">1학년</option> 
    <option value="2">2학년</option> 
    <option value="3">3학년</option> 
    <option value="4">졸업생</option> 
  </select><br><br>
  
  <input type="range" min="0" max="100" step=1 value="0"/><br><br>
  
  <input type="date"/>
  <input type="time"/><br><br>
  
  <input type="submit" value="제출">
</form> 


</body>
</html>

edu/templates/tag_study.html
{% extends "base.html" %}
{% block content %}

    <img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Instagram_logo.svg/150px-Instagram_logo.svg.png"
        width = "100px"
        height = "40px"
    />

    <h2>half_bottle</h2>

    <div>
        <img src = "/static/edu/image/profile.jpg" width = "100px"/> <br/>

        <button>프로필 편집</button>
    </div>

    <p>
        <strong>
            류승엽 (Seungyeop Ryu)<br/>
        </strong>
        작가<br/>
        <a href="{% url 'edu:new_content' %}">새글등록</a>
    </p>

    <ul>
        {% for feed in feed_list %}
            <li>
                {{feed.content}}
                <img src="/media/{{feed.photo}}" width="100px"/>
            </li>
        {% endfor %}
    </ul>

    <p>
        <a href="https://programmers.co.kr/">
            프로그래머스
        </a>
    </p>

    <div>
        <div>
            <div>
                <img src="/static/edu/image/hl 1.jpg" height="35px"/>
            </div>
            <div>
                😃
            </div>
        </div>
        <div>
            <div>
                <img src="/static/edu/image/hl 2.jpg" height="35px"/>
            </div>
            <div>
                😁
            </div>
        </div>
    </div>

    <p>
        게시물<br/>
        팔로워<br/>
        팔로우<br/>
        133<br/>
        408<br/>
        189
    </p>

    <div>
        <img src="/static/edu/image/thumbnails/1.jpg" width="32%">
        <img src="/static/edu/image/thumbnails/2.jpg" width="32%">
        <img src="/static/edu/image/thumbnails/3.jpg" width="32%">
        <img src="/static/edu/image/thumbnails/4.jpg" width="32%">
        <img src="/static/edu/image/thumbnails/5.jpg" width="32%">
        <img src="/static/edu/image/thumbnails/6.jpg" width="32%">
        <img src="/static/edu/image/thumbnails/7.jpg" width="32%">
        <img src="/static/edu/image/thumbnails/8.jpg" width="32%">
        <img src="/static/edu/image/thumbnails/9.jpg" width="32%">
    </div>
{% endblock content %}

edu/templates/upload_form.html
{% extends "base.html" %}
{% block content %}
    <form action="{% url 'edu:new_content'%}" method="POST"
            enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="content"/><br>
        <input type="file" accept="image/*" name="up_photo"/>
        <input type="submit" value="저장"/>
    </form>
{% endblock content %}